export const UserRegistrationType = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAIL: "USER_REGISTER_FAIL",
};

export const UserLoginType = {
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  USER_LOGOUT: "USER_LOGOUT",
};

export const DepositMoneyType = {
  DEPOSIT_MONEY_REQUEST: "DEPOSIT_MONEY_REQUEST",
  DEPOSIT_MONEY_SUCCESS: "DEPOSIT_MONEY_SUCCESS",
  DEPOSIT_MONEY_FAIL: "DEPOSIT_MONEY_FAIL",
};

export const WithdrawMoneyType = {
  WITHDRAW_MONEY_REQUEST: "WITHDRAW_MONEY_REQUEST",
  WITHDRAW_MONEY_SUCCESS: "WITHDRAW_MONEY_SUCCESS",
  WITHDRAW_MONEY_FAIL: "WITHDRAW_MONEY_FAIL",
};

export const UserProfileType = {
  USER_PROFILE_REQUEST: "USER_PROFILE_REQUEST",
  USER_PROFILE_SUCCESS: "USER_PROFILE_SUCCESS",
  USER_PROFILE_FAIL: "USER_PROFILE_FAIL",
  USER_PROFILE_RESET: "USER_PROFILE_RESET",
};
